package com.up.train.model;

import com.up.train.model.base.BaseApply;
import org.eclipse.jetty.deploy.App;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Apply extends BaseApply<Apply> {
	public static final Apply dao = new Apply();

    public List<Apply> findByPhone(String phone) {
        return find("select a.*,o.name from t_apply a " +
                "left join t_organization o on o.id=a.org_id "+
                "where a.user_phone="+phone+
                " ORDER BY id DESC");
    }
    /**
     * 获取该号码已经在该机构报名的信息，判断该号码是否已经报名
     * @param apply
     * @return
     */
    public Apply findApplyingByPhone(Apply apply) {
        return findFirst("select a.*,o.name from t_apply a " +
                "left join t_organization o on o.id=a.org_id "+
                "where a.status=1 and user_phone="+apply.getUserPhone());
    }
    public Apply findByPhone2(String phone) {
        return findFirst("select * from t_apply where user_phone="+phone);
    }

    public List<Apply> findByOrgId(String id) {
        String sql = "select * from t_apply where org_id="+id;
        return find(sql);
    }
    public List<Apply> findAllApply(Apply apply) {
        String sql = "select a.*,o.name from t_apply a " +
                "left join t_organization o on o.id=a.org_id "+
                "where 1=1";
        return find(sql);
    }
    /**
     * 查询status为1的CDKEY存在数量
     * @param cdKey
     * @return
     */
    public Long verifyCDKey(String cdKey){
        Long count=findFirst("select count(*) from t_apply where cd_key ='" +cdKey+"' and status=1").get("count(*)");
        return count;
    }


    public Apply findApplyById(String id) {
        return findFirst("select a.*,o.name from t_apply a " +
                "left join t_organization o on o.id=a.org_id "+
                "where a.id="+id);
    }
}
