package com.up.train.model;

import com.up.train.model.base.BaseExam;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Exam extends BaseExam<Exam> {
	public static final Exam dao = new Exam();

    public List<Exam> getList() {
        return find("select * from t_exam");
    }
}
