package com.up.train.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApply<M extends BaseApply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setWxAccount(java.lang.String wxAccount) {
		set("wx_account", wxAccount);
	}

	public java.lang.String getWxAccount() {
		return get("wx_account");
	}

	public void setCdKey(java.lang.String cdKey) {
		set("cd_key", cdKey);
	}

	public java.lang.String getCdKey() {
		return get("cd_key");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setUserPhone(java.lang.String userPhone) {
		set("user_phone", userPhone);
	}

	public java.lang.String getUserPhone() {
		return get("user_phone");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}

	public java.lang.String getOrgId() {
		return get("org_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}

	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public void setUserSurePay(java.lang.Boolean userSurePay) {
		set("user_sure_pay", userSurePay);
	}

	public java.lang.Boolean getUserSurePay() {
		return get("user_sure_pay");
	}

	public void setOrgSurePay(java.lang.Boolean orgSurePay) {
		set("org_sure_pay", orgSurePay);
	}

	public java.lang.Boolean getOrgSurePay() {
		return get("org_sure_pay");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
