package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchaseDetails<M extends BasePurchaseDetails<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPurchaseId(java.lang.Integer purchaseId) {
		set("purchase_id", purchaseId);
	}

	public java.lang.Integer getPurchaseId() {
		return get("purchase_id");
	}

	public void setSkuGoodsId(java.lang.Integer skuGoodsId) {
		set("sku_goods_id", skuGoodsId);
	}

	public java.lang.Integer getSkuGoodsId() {
		return get("sku_goods_id");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

}
