package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMember<M extends BaseMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setHeartImgUrl(java.lang.String heartImgUrl) {
		set("heart_img_url", heartImgUrl);
	}

	public java.lang.String getHeartImgUrl() {
		return get("heart_img_url");
	}

	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}

	public java.lang.String getOpenId() {
		return get("open_id");
	}

	public void setConsumeCount(java.lang.Integer consumeCount) {
		set("consume_count", consumeCount);
	}

	public java.lang.Integer getConsumeCount() {
		return get("consume_count");
	}

	public void setConsumeAmount(java.lang.Double consumeAmount) {
		set("consume_amount", consumeAmount);
	}

	public java.lang.Double getConsumeAmount() {
		return get("consume_amount");
	}

	public void setRebateCount(java.lang.Double rebateCount) {
		set("rebate_count", rebateCount);
	}

	public java.lang.Double getRebateCount() {
		return get("rebate_count");
	}

	public void setRegisterTime(java.util.Date registerTime) {
		set("register_time", registerTime);
	}

	public java.util.Date getRegisterTime() {
		return get("register_time");
	}

	public void setRegisterFrom(java.lang.Integer registerFrom) {
		set("register_from", registerFrom);
	}

	public java.lang.Integer getRegisterFrom() {
		return get("register_from");
	}

	public void setVipGradeId(java.lang.Integer vipGradeId) {
		set("vip_grade_id", vipGradeId);
	}

	public java.lang.Integer getVipGradeId() {
		return get("vip_grade_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setRefundCount(java.lang.Integer refundCount) {
		set("refund_count", refundCount);
	}

	public java.lang.Integer getRefundCount() {
		return get("refund_count");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
