package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePostageProvince<M extends BasePostageProvince<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPtId(java.lang.Integer ptId) {
		set("pt_id", ptId);
	}

	public java.lang.Integer getPtId() {
		return get("pt_id");
	}

	public void setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
	}

	public java.lang.String getProvinceName() {
		return get("province_name");
	}

	public void setPostage(java.lang.Double postage) {
		set("postage", postage);
	}

	public java.lang.Double getPostage() {
		return get("postage");
	}

}
