package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExp<M extends BaseExp<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setImgUrl(java.lang.String imgUrl) {
		set("imgUrl", imgUrl);
	}

	public java.lang.String getImgUrl() {
		return get("imgUrl");
	}

	public void setSimpleName(java.lang.String simpleName) {
		set("simpleName", simpleName);
	}

	public java.lang.String getSimpleName() {
		return get("simpleName");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setExpName(java.lang.String expName) {
		set("expName", expName);
	}

	public java.lang.String getExpName() {
		return get("expName");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

}
