package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegion<M extends BaseRegion<M>> extends Model<M> implements IBean {

	public void setCode(java.lang.Integer code) {
		set("code", code);
	}

	public java.lang.Integer getCode() {
		return get("code");
	}

	public void setParentCode(java.lang.Integer parentCode) {
		set("parentCode", parentCode);
	}

	public java.lang.Integer getParentCode() {
		return get("parentCode");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setFullName(java.lang.String fullName) {
		set("fullName", fullName);
	}

	public java.lang.String getFullName() {
		return get("fullName");
	}

}
