package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBrand<M extends BaseBrand<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNameZh(java.lang.String nameZh) {
		set("name_zh", nameZh);
	}

	public java.lang.String getNameZh() {
		return get("name_zh");
	}

	public void setNameEn(java.lang.String nameEn) {
		set("name_en", nameEn);
	}

	public java.lang.String getNameEn() {
		return get("name_en");
	}

	public void setCountryId(java.lang.Integer countryId) {
		set("country_id", countryId);
	}

	public java.lang.Integer getCountryId() {
		return get("country_id");
	}

	public void setLogoBigUrl(java.lang.String logoBigUrl) {
		set("logo_big_url", logoBigUrl);
	}

	public java.lang.String getLogoBigUrl() {
		return get("logo_big_url");
	}

	public void setLogoSmallUrl(java.lang.String logoSmallUrl) {
		set("logo_small_url", logoSmallUrl);
	}

	public java.lang.String getLogoSmallUrl() {
		return get("logo_small_url");
	}

	public void setBannerUrl(java.lang.String bannerUrl) {
		set("banner_url", bannerUrl);
	}

	public java.lang.String getBannerUrl() {
		return get("banner_url");
	}

	public void setAbout(java.lang.String about) {
		set("about", about);
	}

	public java.lang.String getAbout() {
		return get("about");
	}

	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}

	public java.lang.String getIntroduce() {
		return get("introduce");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setRecommend(java.lang.Boolean recommend) {
		set("recommend", recommend);
	}

	public java.lang.Boolean getRecommend() {
		return get("recommend");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setGoodsSjCount(java.lang.Integer goodsSjCount) {
		set("goods_sj_count", goodsSjCount);
	}

	public java.lang.Integer getGoodsSjCount() {
		return get("goods_sj_count");
	}

	public void setGoodsXjCount(java.lang.Integer goodsXjCount) {
		set("goods_xj_count", goodsXjCount);
	}

	public java.lang.Integer getGoodsXjCount() {
		return get("goods_xj_count");
	}

	public void setTotalStock(java.lang.Integer totalStock) {
		set("total_stock", totalStock);
	}

	public java.lang.Integer getTotalStock() {
		return get("total_stock");
	}

	public void setTotalSales(java.lang.Integer totalSales) {
		set("total_sales", totalSales);
	}

	public java.lang.Integer getTotalSales() {
		return get("total_sales");
	}

	public void setTotalSaleroom(java.lang.Double totalSaleroom) {
		set("total_saleroom", totalSaleroom);
	}

	public java.lang.Double getTotalSaleroom() {
		return get("total_saleroom");
	}

}
