package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysConfig<M extends BaseSysConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setIId(java.lang.Integer iId) {
		set("i_id", iId);
	}

	public java.lang.Integer getIId() {
		return get("i_id");
	}

	public void setKey(java.lang.Integer key) {
		set("key", key);
	}

	public java.lang.Integer getKey() {
		return get("key");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setSimpleName(java.lang.String simpleName) {
		set("simple_name", simpleName);
	}

	public java.lang.String getSimpleName() {
		return get("simple_name");
	}

}
