package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRepestory<M extends BaseRepestory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goods_id");
	}

	public void setSku1Id(java.lang.Integer sku1Id) {
		set("sku1_id", sku1Id);
	}

	public java.lang.Integer getSku1Id() {
		return get("sku1_id");
	}

	public void setSku2Id(java.lang.Integer sku2Id) {
		set("sku2_id", sku2Id);
	}

	public java.lang.Integer getSku2Id() {
		return get("sku2_id");
	}

	public void setSku3Id(java.lang.Integer sku3Id) {
		set("sku3_id", sku3Id);
	}

	public java.lang.Integer getSku3Id() {
		return get("sku3_id");
	}

	public void setSku4Id(java.lang.Integer sku4Id) {
		set("sku4_id", sku4Id);
	}

	public java.lang.Integer getSku4Id() {
		return get("sku4_id");
	}

	public void setSku5Id(java.lang.Integer sku5Id) {
		set("sku5_id", sku5Id);
	}

	public java.lang.Integer getSku5Id() {
		return get("sku5_id");
	}

	public void setMarketPrice(java.lang.Double marketPrice) {
		set("market_price", marketPrice);
	}

	public java.lang.Double getMarketPrice() {
		return get("market_price");
	}

	public void setPromotePrice(java.lang.Double promotePrice) {
		set("promote_price", promotePrice);
	}

	public java.lang.Double getPromotePrice() {
		return get("promote_price");
	}

	public void setRepertory(java.lang.Integer repertory) {
		set("repertory", repertory);
	}

	public java.lang.Integer getRepertory() {
		return get("repertory");
	}

	public void setGoodsNumber(java.lang.String goodsNumber) {
		set("goods_number", goodsNumber);
	}

	public java.lang.String getGoodsNumber() {
		return get("goods_number");
	}

	public void setPutaway(java.lang.Integer putaway) {
		set("putaway", putaway);
	}

	public java.lang.Integer getPutaway() {
		return get("putaway");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setImg1Url(java.lang.String img1Url) {
		set("img1_url", img1Url);
	}

	public java.lang.String getImg1Url() {
		return get("img1_url");
	}

	public void setBrandId(java.lang.Integer brandId) {
		set("brand_id", brandId);
	}

	public java.lang.Integer getBrandId() {
		return get("brand_id");
	}

	public void setNameZh(java.lang.String nameZh) {
		set("name_zh", nameZh);
	}

	public java.lang.String getNameZh() {
		return get("name_zh");
	}

	public void setOneCatName(java.lang.String oneCatName) {
		set("one_cat_name", oneCatName);
	}

	public java.lang.String getOneCatName() {
		return get("one_cat_name");
	}

	public void setTowCatName(java.lang.String towCatName) {
		set("tow_cat_name", towCatName);
	}

	public java.lang.String getTowCatName() {
		return get("tow_cat_name");
	}

	public void setMainNumber(java.lang.String mainNumber) {
		set("main_number", mainNumber);
	}

	public java.lang.String getMainNumber() {
		return get("main_number");
	}

	public void setSku1Name(java.lang.String sku1Name) {
		set("sku1_name", sku1Name);
	}

	public java.lang.String getSku1Name() {
		return get("sku1_name");
	}

	public void setSku2Name(java.lang.String sku2Name) {
		set("sku2_name", sku2Name);
	}

	public java.lang.String getSku2Name() {
		return get("sku2_name");
	}

	public void setSku3Name(java.lang.String sku3Name) {
		set("sku3_name", sku3Name);
	}

	public java.lang.String getSku3Name() {
		return get("sku3_name");
	}

}
