package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		set("serial_number", serialNumber);
	}

	public java.lang.String getSerialNumber() {
		return get("serial_number");
	}

	public void setPaySn(java.lang.String paySn) {
		set("pay_sn", paySn);
	}

	public java.lang.String getPaySn() {
		return get("pay_sn");
	}

	public void setMemberId(java.lang.Integer memberId) {
		set("member_id", memberId);
	}

	public java.lang.Integer getMemberId() {
		return get("member_id");
	}

	public void setMemberAddrId(java.lang.Integer memberAddrId) {
		set("member_addr_id", memberAddrId);
	}

	public java.lang.Integer getMemberAddrId() {
		return get("member_addr_id");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setVipDiscounts(java.lang.Double vipDiscounts) {
		set("vip_discounts", vipDiscounts);
	}

	public java.lang.Double getVipDiscounts() {
		return get("vip_discounts");
	}

	public void setDeliveryType(java.lang.Integer deliveryType) {
		set("delivery_type", deliveryType);
	}

	public java.lang.Integer getDeliveryType() {
		return get("delivery_type");
	}

	public void setCouponAmount(java.lang.Double couponAmount) {
		set("coupon_amount", couponAmount);
	}

	public java.lang.Double getCouponAmount() {
		return get("coupon_amount");
	}

	public void setMemberCouponId(java.lang.Integer memberCouponId) {
		set("member_coupon_id", memberCouponId);
	}

	public java.lang.Integer getMemberCouponId() {
		return get("member_coupon_id");
	}

	public void setRebate(java.lang.Double rebate) {
		set("rebate", rebate);
	}

	public java.lang.Double getRebate() {
		return get("rebate");
	}

	public void setPostagePrice(java.lang.Double postagePrice) {
		set("postage_price", postagePrice);
	}

	public java.lang.Double getPostagePrice() {
		return get("postage_price");
	}

	public void setRealPrice(java.lang.Double realPrice) {
		set("real_price", realPrice);
	}

	public java.lang.Double getRealPrice() {
		return get("real_price");
	}

	public void setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
	}

	public java.lang.Integer getPayType() {
		return get("pay_type");
	}

	public void setLeaveWord(java.lang.String leaveWord) {
		set("leave_word", leaveWord);
	}

	public java.lang.String getLeaveWord() {
		return get("leave_word");
	}

	public void setDeliverReamrk(java.lang.String deliverReamrk) {
		set("deliver_reamrk", deliverReamrk);
	}

	public java.lang.String getDeliverReamrk() {
		return get("deliver_reamrk");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setFrom(java.lang.Integer from) {
		set("from", from);
	}

	public java.lang.Integer getFrom() {
		return get("from");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setStatusReturns(java.lang.Integer statusReturns) {
		set("status_returns", statusReturns);
	}

	public java.lang.Integer getStatusReturns() {
		return get("status_returns");
	}

	public void setTimeCreate(java.util.Date timeCreate) {
		set("time_create", timeCreate);
	}

	public java.util.Date getTimeCreate() {
		return get("time_create");
	}

	public void setTimePay(java.util.Date timePay) {
		set("time_pay", timePay);
	}

	public java.util.Date getTimePay() {
		return get("time_pay");
	}

	public void setTimeDeliver(java.util.Date timeDeliver) {
		set("time_deliver", timeDeliver);
	}

	public java.util.Date getTimeDeliver() {
		return get("time_deliver");
	}

	public void setTimeReceiving(java.util.Date timeReceiving) {
		set("time_receiving", timeReceiving);
	}

	public java.util.Date getTimeReceiving() {
		return get("time_receiving");
	}

	public void setTimeReturns(java.util.Date timeReturns) {
		set("time_returns", timeReturns);
	}

	public java.util.Date getTimeReturns() {
		return get("time_returns");
	}

	public void setTimeReturnsAgree(java.util.Date timeReturnsAgree) {
		set("time_returns_agree", timeReturnsAgree);
	}

	public java.util.Date getTimeReturnsAgree() {
		return get("time_returns_agree");
	}

	public void setTimeReturnsDeliver(java.util.Date timeReturnsDeliver) {
		set("time_returns_deliver", timeReturnsDeliver);
	}

	public java.util.Date getTimeReturnsDeliver() {
		return get("time_returns_deliver");
	}

	public void setTimeReturnsFinish(java.util.Date timeReturnsFinish) {
		set("time_returns_finish", timeReturnsFinish);
	}

	public java.util.Date getTimeReturnsFinish() {
		return get("time_returns_finish");
	}

	public void setExpressage(java.lang.String expressage) {
		set("expressage", expressage);
	}

	public java.lang.String getExpressage() {
		return get("expressage");
	}

	public void setLogisticsNumber(java.lang.String logisticsNumber) {
		set("logistics_number", logisticsNumber);
	}

	public java.lang.String getLogisticsNumber() {
		return get("logistics_number");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}

	public java.lang.String getContact() {
		return get("contact");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public void setReturnsAddress(java.lang.String returnsAddress) {
		set("returns_address", returnsAddress);
	}

	public java.lang.String getReturnsAddress() {
		return get("returns_address");
	}

	public void setReturnsRemark(java.lang.String returnsRemark) {
		set("returns_remark", returnsRemark);
	}

	public java.lang.String getReturnsRemark() {
		return get("returns_remark");
	}

	public void setReturnsExpressage(java.lang.String returnsExpressage) {
		set("returns_expressage", returnsExpressage);
	}

	public java.lang.String getReturnsExpressage() {
		return get("returns_expressage");
	}

	public void setReturnsLogisticsNumber(java.lang.String returnsLogisticsNumber) {
		set("returns_logistics_number", returnsLogisticsNumber);
	}

	public java.lang.String getReturnsLogisticsNumber() {
		return get("returns_logistics_number");
	}

	public void setReturnsReceivingRamark(java.lang.String returnsReceivingRamark) {
		set("returns_receiving_ramark", returnsReceivingRamark);
	}

	public java.lang.String getReturnsReceivingRamark() {
		return get("returns_receiving_ramark");
	}

	public void setSuccessRebate(java.lang.Double successRebate) {
		set("success_rebate", successRebate);
	}

	public java.lang.Double getSuccessRebate() {
		return get("success_rebate");
	}

}
