package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSkuGoods<M extends BaseSkuGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goods_id");
	}

	public void setSku1Id(java.lang.Integer sku1Id) {
		set("sku1_id", sku1Id);
	}

	public java.lang.Integer getSku1Id() {
		return get("sku1_id");
	}

	public void setSku2Id(java.lang.Integer sku2Id) {
		set("sku2_id", sku2Id);
	}

	public java.lang.Integer getSku2Id() {
		return get("sku2_id");
	}

	public void setSku3Id(java.lang.Integer sku3Id) {
		set("sku3_id", sku3Id);
	}

	public java.lang.Integer getSku3Id() {
		return get("sku3_id");
	}

	public void setSku4Id(java.lang.Integer sku4Id) {
		set("sku4_id", sku4Id);
	}

	public java.lang.Integer getSku4Id() {
		return get("sku4_id");
	}

	public void setSku5Id(java.lang.Integer sku5Id) {
		set("sku5_id", sku5Id);
	}

	public java.lang.Integer getSku5Id() {
		return get("sku5_id");
	}

	public void setMarketPrice(java.lang.Double marketPrice) {
		set("market_price", marketPrice);
	}

	public java.lang.Double getMarketPrice() {
		return get("market_price");
	}

	public void setPromotePrice(java.lang.Double promotePrice) {
		set("promote_price", promotePrice);
	}

	public java.lang.Double getPromotePrice() {
		return get("promote_price");
	}

	public void setRepertory(java.lang.Integer repertory) {
		set("repertory", repertory);
	}

	public java.lang.Integer getRepertory() {
		return get("repertory");
	}

	public void setGoodsNumber(java.lang.String goodsNumber) {
		set("goods_number", goodsNumber);
	}

	public java.lang.String getGoodsNumber() {
		return get("goods_number");
	}

	public void setPutaway(java.lang.Integer putaway) {
		set("putaway", putaway);
	}

	public java.lang.Integer getPutaway() {
		return get("putaway");
	}

}
