package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConcern<M extends BaseConcern<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFromMemberId(java.lang.Integer fromMemberId) {
		set("from_member_id", fromMemberId);
	}

	public java.lang.Integer getFromMemberId() {
		return get("from_member_id");
	}

	public void setFromMemberName(java.lang.String fromMemberName) {
		set("from_member_name", fromMemberName);
	}

	public java.lang.String getFromMemberName() {
		return get("from_member_name");
	}

	public void setToMemberId(java.lang.Integer toMemberId) {
		set("to_member_id", toMemberId);
	}

	public java.lang.Integer getToMemberId() {
		return get("to_member_id");
	}

	public void setToMemberName(java.lang.String toMemberName) {
		set("to_member_name", toMemberName);
	}

	public java.lang.String getToMemberName() {
		return get("to_member_name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
