package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberCoupon<M extends BaseMemberCoupon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCdkey(java.lang.String cdkey) {
		set("cdkey", cdkey);
	}

	public java.lang.String getCdkey() {
		return get("cdkey");
	}

	public void setCouponId(java.lang.Integer couponId) {
		set("coupon_id", couponId);
	}

	public java.lang.Integer getCouponId() {
		return get("coupon_id");
	}

	public void setMemberIdGet(java.lang.Integer memberIdGet) {
		set("member_id_get", memberIdGet);
	}

	public java.lang.Integer getMemberIdGet() {
		return get("member_id_get");
	}

	public void setMemberIdExchange(java.lang.Integer memberIdExchange) {
		set("member_id_exchange", memberIdExchange);
	}

	public java.lang.Integer getMemberIdExchange() {
		return get("member_id_exchange");
	}

	public void setMemberIdUse(java.lang.Integer memberIdUse) {
		set("member_id_use", memberIdUse);
	}

	public java.lang.Integer getMemberIdUse() {
		return get("member_id_use");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setAllot(java.lang.Boolean allot) {
		set("allot", allot);
	}

	public java.lang.Boolean getAllot() {
		return get("allot");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("order_id");
	}

	public void setOrderAmount(java.lang.Double orderAmount) {
		set("order_amount", orderAmount);
	}

	public java.lang.Double getOrderAmount() {
		return get("order_amount");
	}

	public void setUseTime(java.util.Date useTime) {
		set("use_time", useTime);
	}

	public java.util.Date getUseTime() {
		return get("use_time");
	}

}
