package com.up.infant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOneCatId(java.lang.Integer oneCatId) {
		set("one_cat_id", oneCatId);
	}

	public java.lang.Integer getOneCatId() {
		return get("one_cat_id");
	}

	public void setTowCatId(java.lang.Integer towCatId) {
		set("tow_cat_id", towCatId);
	}

	public java.lang.Integer getTowCatId() {
		return get("tow_cat_id");
	}

	public void setBrandId(java.lang.Integer brandId) {
		set("brand_id", brandId);
	}

	public java.lang.Integer getBrandId() {
		return get("brand_id");
	}

	public void setMainNumber(java.lang.String mainNumber) {
		set("main_number", mainNumber);
	}

	public java.lang.String getMainNumber() {
		return get("main_number");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMarketPrice(java.lang.Double marketPrice) {
		set("market_price", marketPrice);
	}

	public java.lang.Double getMarketPrice() {
		return get("market_price");
	}

	public void setPromotePrice(java.lang.Double promotePrice) {
		set("promote_price", promotePrice);
	}

	public java.lang.Double getPromotePrice() {
		return get("promote_price");
	}

	public void setAbout(java.lang.String about) {
		set("about", about);
	}

	public java.lang.String getAbout() {
		return get("about");
	}

	public void setApplySex(java.lang.Integer applySex) {
		set("apply_sex", applySex);
	}

	public java.lang.Integer getApplySex() {
		return get("apply_sex");
	}

	public void setApplyAge(java.lang.String applyAge) {
		set("apply_age", applyAge);
	}

	public java.lang.String getApplyAge() {
		return get("apply_age");
	}

	public void setApplySeason(java.lang.String applySeason) {
		set("apply_season", applySeason);
	}

	public java.lang.String getApplySeason() {
		return get("apply_season");
	}

	public void setTexture(java.lang.String texture) {
		set("texture", texture);
	}

	public java.lang.String getTexture() {
		return get("texture");
	}

	public void setImg1Url(java.lang.String img1Url) {
		set("img1_url", img1Url);
	}

	public java.lang.String getImg1Url() {
		return get("img1_url");
	}

	public void setImg2Url(java.lang.String img2Url) {
		set("img2_url", img2Url);
	}

	public java.lang.String getImg2Url() {
		return get("img2_url");
	}

	public void setImg3Url(java.lang.String img3Url) {
		set("img3_url", img3Url);
	}

	public java.lang.String getImg3Url() {
		return get("img3_url");
	}

	public void setImg4Url(java.lang.String img4Url) {
		set("img4_url", img4Url);
	}

	public java.lang.String getImg4Url() {
		return get("img4_url");
	}

	public void setImg5Url(java.lang.String img5Url) {
		set("img5_url", img5Url);
	}

	public java.lang.String getImg5Url() {
		return get("img5_url");
	}

	public void setTagId(java.lang.Integer tagId) {
		set("tag_id", tagId);
	}

	public java.lang.Integer getTagId() {
		return get("tag_id");
	}

	public void setProductionArea(java.lang.String productionArea) {
		set("production_area", productionArea);
	}

	public java.lang.String getProductionArea() {
		return get("production_area");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public void setPostage(java.lang.Integer postage) {
		set("postage", postage);
	}

	public java.lang.Integer getPostage() {
		return get("postage");
	}

	public void setPackingList(java.lang.String packingList) {
		set("packing_list", packingList);
	}

	public java.lang.String getPackingList() {
		return get("packing_list");
	}

	public void setAfterSales(java.lang.String afterSales) {
		set("after_sales", afterSales);
	}

	public java.lang.String getAfterSales() {
		return get("after_sales");
	}

	public void setPutaway(java.lang.Integer putaway) {
		set("putaway", putaway);
	}

	public java.lang.Integer getPutaway() {
		return get("putaway");
	}

	public void setSkuRepertory(java.lang.Integer skuRepertory) {
		set("sku_repertory", skuRepertory);
	}

	public java.lang.Integer getSkuRepertory() {
		return get("sku_repertory");
	}

	public void setTotalSales(java.lang.Integer totalSales) {
		set("total_sales", totalSales);
	}

	public java.lang.Integer getTotalSales() {
		return get("total_sales");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setPutawayTime(java.util.Date putawayTime) {
		set("putaway_time", putawayTime);
	}

	public java.util.Date getPutawayTime() {
		return get("putaway_time");
	}

	public void setSoldoutTime(java.util.Date soldoutTime) {
		set("soldout_time", soldoutTime);
	}

	public java.util.Date getSoldoutTime() {
		return get("soldout_time");
	}

	public void setRecommend(java.lang.Boolean recommend) {
		set("recommend", recommend);
	}

	public java.lang.Boolean getRecommend() {
		return get("recommend");
	}

	public void setViewCount(java.lang.Integer viewCount) {
		set("view_count", viewCount);
	}

	public java.lang.Integer getViewCount() {
		return get("view_count");
	}

}
