package com.up.infant.model;

import com.up.infant.model.base.BaseCart;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cart extends BaseCart<Cart> {
    public static final Cart dao = new Cart();

    public Cart getByMemberIdAndSkuId(int memberId, int skuGoodsId) {
        String sql = "SELECT * FROM t_cart WHERE t_cart.`member_id`=" + memberId + " AND t_cart.`sku_goods_id`=" + skuGoodsId;
        return findFirst(sql);
    }

    public Cart getByMemberIdAndCartId(int memberId, int cartId) {
        String sql = "select * from t_cart where t_cart.`member_id`="+memberId+" and t_cart.`id`="+cartId;
        return findFirst(sql);
    }

    public List<Cart> getCart(int memberId) {
        String sql = "SELECT t_brand.*,t_country.`name` AS country_name,t_country.`img_url` AS country_img,\n" +
                "\tt_cart.`id` AS cart_id,t_cart.`sku_goods_id`,t_cart.`count`,t_cart.`from`,\n" +
                "\tt_goods.`name`,t_goods.`img1_url`,t_goods.`id` as goods_id,\n" +
                "\tt_sku_goods.`goods_number`,t_sku_goods.`market_price`,t_sku_goods.`promote_price`,\n" +
                "\tt_sku1.`name` AS name1,\n" +
                "\tt_sku2.`name` AS name2,\n" +
                "\tt_sku3.`name` AS name3\n" +
//                "\tt_sku4.`name` AS name4,\n" +
//                "\tt_sku5.`name` AS name5\n" +
                "FROM t_cart t_cart\n" +
                "LEFT JOIN t_sku_goods t_sku_goods ON t_sku_goods.`id`=t_cart.`sku_goods_id`\n" +
                "LEFT JOIN t_sku t_sku1 ON t_sku1.`id`=t_sku_goods.`sku1_id`\n" +
                "LEFT JOIN t_sku t_sku2 ON t_sku2.`id`=t_sku_goods.`sku2_id`\n" +
                "LEFT JOIN t_sku t_sku3 ON t_sku3.`id`=t_sku_goods.`sku3_id`\n" +
//                "LEFT JOIN t_sku t_sku4 ON t_sku4.`id`=t_sku_goods.`sku4_id`\n" +
//                "LEFT JOIN t_sku t_sku5 ON t_sku5.`id`=t_sku_goods.`sku5_id`\n" +
                "LEFT JOIN t_goods t_goods ON t_goods.`id`=t_sku_goods.`goods_id` \n" +
                "LEFT JOIN t_brand t_brand ON t_brand.`id`=t_goods.`brand_id`\n" +
                "LEFT JOIN t_country t_country ON t_country.`id`=t_brand.`country_id`\n" +
                "WHERE t_cart.member_id=" + memberId + " AND t_sku_goods.`putaway`=1 AND t_goods.`putaway`=1 AND t_brand.`status`=1\n" +
                "ORDER BY t_brand.`id` ";
        return find(sql);
    }
}
