package com.up.infant.model;

import com.jfinal.plugin.activerecord.Db;
import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseCategory;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public static final Category dao = new Category();

	public static final String table="t_category t_category";
	public static final String id="t_category.id";
	public static final String name="t_category.cat_name";
	public static final String pId="t_category.parent_id";
	public static final String desc="t_category.cat_desc";
	public static final String status="t_category.status";


	public List<Category> getList(int parentId ){
		String sql= Sql.select("*")+Sql.from(table);
		if (parentId>=0){
			Map<String,String> map=new HashMap<String, String>();
			map.put(pId,parentId+"");
			map.put(status,"0");
			sql=sql+Sql.where(map);
		}

		return find(sql);
	}

	public void deleteBatch(int pId){
		List<Category> categories=this.getList(pId);
		/*Object[][] objs = new Object[categories.size()][1];
		for(int i = 0;i<categories.size();i++){
			objs[i][0] = categories.get(i).getId();
		}
		Db.batch("delete from t_category where id = ?",objs,categories.size());*/
		for(int i = 0;i<categories.size();i++){
			 categories.get(i).setStatus(1);
		}
		Db.batchUpdate(categories,categories.size());
	}
}
