package com.up.infant.model;

import com.jfinal.plugin.activerecord.Page;
import com.up.infant.model.base.BaseCollect;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collect extends BaseCollect<Collect> {
    public static final Collect dao = new Collect();

    public Collect hasCollect(int memberId, int goodsId) {
        String sql = "select * from t_collect where goods_id=" + goodsId + " and member_id=" + memberId;
        return  findFirst(sql);
    }

    public Page<Collect> getMemberList(int pageSize, int pageNo, int memberId) {
        String select = "SELECT c.*,g.name,g.img1_url,b.name_zh,c1.cat_name AS one_cat_name,c2.cat_name AS tow_cat_name,g.main_number,g.market_price";
        String sqlExceptSelect = "from t_collect AS c"+
                " LEFT JOIN t_goods AS g ON g.id = c.goods_id"+
                " LEFT JOIN t_brand AS b ON g.brand_id = b.id"+
                " LEFT JOIN t_category AS c1 ON g.one_cat_id = c1.id"+
                " LEFT JOIN t_category AS c2 ON g.tow_cat_id = c2.id"+
                " WHERE 1=1 and c.member_id="+memberId+" order by c.create_time ";
        return paginate(pageNo, pageSize, select, sqlExceptSelect);
    }

    public List<Collect> getCollect(int memberId){
       String sql="  SELECT t_collect.`id` AS collect_id ,t_collect.`create_time` AS collect_time, t_goods.*,t_goods_points.`sell_point`\n" +
               "  FROM t_collect t_collect\n" +
               "  LEFT JOIN t_goods t_goods ON t_goods.`id`=t_collect.`goods_id`\n" +
               "  LEFT JOIN t_goods_points t_goods_points ON t_goods_points.`goods_id`=t_goods.`id` \n" +
               "  WHERE t_collect.`member_id`="+memberId+" AND t_goods.`putaway`=1\n" +
               "  GROUP BY t_goods.`id`\n" +
               "   ORDER BY t_collect.create_time DESC";
        return find(sql);
    }

    public Page<Collect> getPageCollect(int pageSize, int pageNo, int memberId){
        String select ="SELECT t_collect.`id` AS collect_id ,t_collect.`create_time` AS collect_time, t_goods.*,t_goods_points.`sell_point`";
        String sqlExceptSelect=   "  FROM t_collect t_collect\n" +
                "  LEFT JOIN t_goods t_goods ON t_goods.`id`=t_collect.`goods_id`\n" +
                "  LEFT JOIN t_goods_points t_goods_points ON t_goods_points.`goods_id`=t_goods.`id` \n" +
                "  WHERE t_collect.`member_id`="+memberId+" AND t_goods.`putaway`=1\n" +
                "  GROUP BY t_goods.`id`\n" +
                "   ORDER BY t_collect.create_time DESC";
        return paginate(pageNo, pageSize,true, select, sqlExceptSelect);
    }
}
