package com.up.infant.model;

import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseCountry;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Country extends BaseCountry<Country> {
	public static final Country dao = new Country();

	public static final String table="t_country t_country";
	public static final String id="t_country.id";
	public static final String name="t_country.name";
	public static final String img="t_country.img_url";
	public static final String status="t_country.status";

	public List<Country> getList(){
		String sql= "select * from t_country t where t.status=0";
		return find(sql);
	}


}
