package com.up.infant.model;

import com.jfinal.plugin.activerecord.Page;
import com.up.common.utils.TextUtils;
import com.up.infant.model.base.BaseCoupon;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coupon extends BaseCoupon<Coupon> {
	public static final Coupon dao = new Coupon();

	public static final String table="t_coupon t_coupon";
	public static final String id="t_coupon.id";
	public static final String CDKey="t_coupon.cdkey";
	public static final String title="t_coupon.title";
	public static final String sTime="t_coupon.start_time";
	public static final String eTime="t_coupon.end_time";
	public static final String iCount="t_coupon.issue_count";
	public static final String gCount="t_coupon.get_count";
	public static final String uCount="t_coupon.use_count";
	public static final String gType="t_coupon.get_type";
	public static final String type="t_coupon.type";
	public static final String tInfo="t_coupon.type_info";
	public static final String cTime="t_coupon.create_time";
	public static final String expand="t_coupon.get_type_expand";
	public static final String dCount="t_coupon.day_count";
	public static final String des="t_coupon.des";


	/**
	 * 查询CDKEY存在数量
	 * @param cdKey
	 * @return
	 */
	public Long verifyCDKey(String cdKey){
		Long count=findFirst("select count(*) from t_coupon where cdkey ='" +cdKey+"'").get("count(*)");
		return count;
	}

	public Coupon getByCdKey(String cdKey){
		String sql="SELECT * FROM t_coupon WHERE cdkey='"+cdKey+"'";
		return findFirst(sql);

	}

    public Page<Coupon> getList(Coupon coupon, int pageNo, int pageSize) {
		String sqlExceptSelect = "from t_coupon t where 1=1";
		if (coupon.getGetType()!=null){//0和1手动分配，2：自动分配
			if(coupon.getGetType()==0||coupon.getGetType()==1){
				sqlExceptSelect +=" AND (t.get_type=1 OR t.get_type=0)";
			}
			else {
				sqlExceptSelect +=" AND t.get_type="+coupon.getGetType();
			}
		}
		if (coupon.getCdkey()!=null){
			sqlExceptSelect +=" AND t.cdkey="+coupon.getCdkey();
		}
		sqlExceptSelect +=" order by id DESC";
		Page<Coupon> page = paginate(pageNo, pageSize, "select *", sqlExceptSelect);
		for (int i =0;i<page.getList().size();i++){
			List<MemberCoupon> memberCouponList = MemberCoupon.dao.getByCouponById(page.getList().get(i).getId());
			int get_count = 0;//已领取
			int use_count = 0;//已使用
			int overdue = 0;//已过期未使用
			for (int j = 0;j<memberCouponList.size();j++){
				if (memberCouponList.get(j).getMemberIdGet()!=null){
					get_count ++;
				}
				if (memberCouponList.get(j).getStatus()==1){
					use_count ++;
				}
				if(memberCouponList.get(j).getStatus()==0&&page.getList().get(i).getEndTime().getTime()<=new Date().getTime()){
					overdue ++;
				}
			}
			page.getList().get(i).put("getCount",get_count);
			page.getList().get(i).put("useCount",use_count);
			page.getList().get(i).put("overdue",overdue);
		}
		return page;
    }

	/**
	 * 获取用户点击领取的优惠劵
	 * @return
	 */
	public List<Coupon> getUserClickCouponList() {
		String sql = "select * from t_coupon t where t.get_type=0 order by t.id DESC";
		return find(sql);
	}
}
