package com.up.infant.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseCustomPage;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomPage extends BaseCustomPage<CustomPage> {
	public static final CustomPage dao = new CustomPage();

	public static final String table="t_custom_page t_custom_page";
	public static final String id="t_custom_page.id";
	public static final String type="t_custom_page.type";
	public static final String isShow="t_custom_page.is_show";
	public static final String title="t_custom_page.title";
	public static final String note="t_custom_page.note";
	public static final String content="t_custom_page.content";
	public static final String time="t_custom_page.create_time";

	/**
	 * 返回单页列表
	 * @param pageNo
	 * @param pageSize
	 * @return
	 */
	public Page<CustomPage> getCustomPage(int pageNo,int pageSize){
		String sql= Sql.select(id,type,title,note,time,isShow) +Sql.from(table);
		return paginate(pageNo, pageSize, Sql.select(id,type,title,note,time,isShow), Sql.from(table)+Sql.orderBy(time,false));
	}

	/**
	 * 返回单页详情
	 * @param pId
	 * @return
	 */
	public CustomPage getPageInfo(int pId){
		Map<String,String> where=new HashMap<String, String>();
		where.put(id,pId+"");
		String sql= Sql.select(id,title,note,time,content,isShow)+Sql.from(table)+Sql.where(where);
		return findFirst(sql);
	}

	public CustomPage getInfo(int pType){
		Map<String,String> where=new HashMap<String, String>();
		where.put(type,pType+"");
		where.put(isShow,"0");
		String sql= Sql.select(id,title,note,time,content,isShow)+Sql.from(table)+Sql.where(where)+Sql.orderBy(time,false);
		return findFirst(sql);
	}


    public List<CustomPage> getList() {
		String sql= Sql.select("*")+Sql.from(table);
		return find(sql);
    }

    public CustomPage specifyInfo(String title){
		String sql="SELECT * FROM t_custom_page WHERE t_custom_page.`title`='"+title+"' AND is_show=0";
		return findFirst(sql);

	}
}
