package com.up.infant.model;

import com.up.infant.model.base.BaseExp;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Exp extends BaseExp<Exp> {
	public static final Exp dao = new Exp();

	public Exp getExp(String com){
		String sql="SELECT * FROM t_exp WHERE expName='"+com+"'";
		return findFirst(sql);
	}
	public List<Exp> getList(){
		String sql = "SELECT * FROM t_exp";
		return find(sql);
	}
}
