package com.up.infant.model;

import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseGoodsTag;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsTag extends BaseGoodsTag<GoodsTag> {
	public static final GoodsTag dao = new GoodsTag();

	public static final String table="t_goods_tag t_goods_tag";
	public static final String id="t_goods_tag.id";
	public static final String name="t_goods_tag.name";
	public static final String img="t_goods_tag.img_url";

	public List<GoodsTag> getList(){
		String sql= Sql.select(id,name,img)+Sql.from(table);
		return find(sql);
	}
}
