package com.up.infant.model;

import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseIdentifying;
import com.up.infant.model.res.ConfigRes;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Identifying extends BaseIdentifying<Identifying> {
	public static final Identifying dao = new Identifying();

	public static final String table="t_identifying t_identifying";
	public static final String id="t_identifying.id";
	public static final String title="t_identifying.title";
	public static final String identifying="t_identifying.identifying";

	public List<Identifying> getList(){
		String sql= Sql.select(id,title,identifying)+Sql.from(table)+Sql.orderBy(id,true);
		return find(sql);
	}

	public List<Identifying> getTypeList(int iId){
		Map<String,String> map=new HashMap<String, String>();
		map.put(id,iId+"");
		String sql= Sql.select(id,title,identifying)+Sql.from(table)+Sql.where(map)+Sql.orderBy(id,true);
		return find(sql);
	}

//	public List<ConfigRes> getAll(){
//		String sql= Sql.select(id,title,identifying)+Sql.from(table)+Sql.orderBy(id,true);
//		List<Identifying> list=find(sql);
//		List<ConfigRes> resList=new ArrayList<ConfigRes>();
//		for (int i=0;i<list.size();i++){
//
//		}
//	}

	public List<Identifying> getAppList(){
		Map<String,String> map=new HashMap<String, String>();
		String sql= Sql.select(id,title,identifying)+Sql.from(table)+Sql.orderBy(id,true);
		return find(sql);
	}
}
