package com.up.infant.model;

import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseMemberChild;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberChild extends BaseMemberChild<MemberChild> {
	public static final MemberChild dao = new MemberChild();

	public static final String table="t_member_child t_member_child";
	public static final String id="t_member_child.id";
	public static final String mId="t_member_child.member_id";
	public static final String sex="t_member_child.sex";
	public static final String birthday="t_member_child.birthday";

	public List<MemberChild> getChild(int memberId){
		Map<String,String> map=new HashMap<String, String>();
		map.put(mId,memberId+"");
		String sql= Sql.select("*")+Sql.from(table)+Sql.where(map);
		return find(sql);
	}

}
