package com.up.infant.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.up.common.utils.TextUtils;
import com.up.infant.model.base.BaseOrderGoods;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderGoods extends BaseOrderGoods<OrderGoods> {
	public static final OrderGoods dao = new OrderGoods();

	public List<OrderGoods> getList(int orderId){
		String sql="\n" +
				"SELECT  t_goods.`id`,t_goods.`name`,\n" +
				"\tt_sku_goods.`goods_number`,t_sku_goods.`promote_price`,t_sku_goods.`market_price`,\n" +
				"\tt_order_goods.`count`,\n" +
				"\t\n" +
				"\tt_sku1.`name` AS name1,\n" +
				"\tt_sku2.`name` AS name2,\n" +
				"\tt_sku3.`name` AS name3,\n" +
				"\tt_sku4.`name` AS name4,\n" +
				"\tt_sku5.`name` AS name5\n" +
				"FROM t_order_goods  t_order_goods\n" +
				"LEFT JOIN t_sku_goods t_sku_goods ON t_sku_goods.`id`=t_order_goods.`sku_goods_id`\n" +
				"LEFT JOIN t_sku t_sku1 ON t_sku1.`id`=t_sku_goods.`sku1_id`\n" +
				"LEFT JOIN t_sku t_sku2 ON t_sku2.`id`=t_sku_goods.`sku2_id`\n" +
				"LEFT JOIN t_sku t_sku3 ON t_sku3.`id`=t_sku_goods.`sku3_id`\n" +
				"LEFT JOIN t_sku t_sku4 ON t_sku4.`id`=t_sku_goods.`sku4_id`\n" +
				"LEFT JOIN t_sku t_sku5 ON t_sku5.`id`=t_sku_goods.`sku5_id`\n" +
				"LEFT JOIN t_goods t_goods ON t_goods.`id`=t_sku_goods.`goods_id` \n" +
				"WHERE t_order_goods.`order_id`="+orderId;
		return find(sql);
	}
	//价格属性直接取，不必取sku中取
	public List<OrderGoods> getList2(int orderId){
		String sql="SELECT  t_goods.`id`,t_goods.`name`,\n" +
				"\tt_order_goods.`goods_sn`,\n" +
				"\tt_order_goods.`count`,t_order_goods.`price`,t_order_goods.`dis_price`\n" +
				"FROM t_order_goods  t_order_goods\n" +
				"LEFT JOIN t_sku_goods t_sku_goods ON t_sku_goods.`id`=t_order_goods.`sku_goods_id`\n" +
				"LEFT JOIN t_goods t_goods ON t_goods.`id`=t_sku_goods.`goods_id` \n" +
				"WHERE t_order_goods.`order_id`="+orderId;
		return find(sql);
	}

    public void addBatch(List<OrderGoods> list) {
		Db.batchSave(list,list.size());
	}

	public List<OrderGoods> getOrderGoods(int orderId){
		String sql="SELECT  t_goods.`id`,t_goods.`name`,t_goods.`img1_url`,\n" +
				"\tt_order_goods.`goods_sn`,t_order_goods.sku_goods_id ,\n" +
				"\tt_order_goods.`count`,t_order_goods.`price`,t_order_goods.`dis_price`,t_order_goods.`sku_info`,\n" +
				"\tt_brand.`name_zh`\n" +
				"\tFROM t_order_goods  t_order_goods\n" +
				"\tLEFT JOIN t_sku_goods t_sku_goods ON t_sku_goods.`id`=t_order_goods.`sku_goods_id`\n" +
				"\tLEFT JOIN t_goods t_goods ON t_goods.`id`=t_sku_goods.`goods_id` \n" +
				"\tLEFT JOIN t_brand t_brand ON t_brand.`id`=t_goods.`brand_id` \n" +
				"\tWHERE t_order_goods.`order_id`="+orderId;
		return find(sql);
	}
	public Page<OrderGoods> getPage(Integer brandId,int pageNo, int pageSize){
		String select = "SELECT t.*,g.name,g.img1_url,sg.goods_number,m.nickname,o.serial_number,o.type,o.from,o.status,o.status_returns";
		String sqlExceptSelect = "from t_order_goods AS t"+
				" LEFT JOIN t_order AS o ON o.id = t.order_id"+
				" LEFT JOIN t_sku_goods AS sg ON sg.id = t.sku_goods_id"+
				" LEFT JOIN t_goods AS g ON g.id = sg.goods_id"+
				" LEFT JOIN t_member AS m ON m.id = o.member_id"+
				" WHERE 1=1";
		if (brandId != null) {
			sqlExceptSelect += " AND g.brand_id=" + brandId;
		}
		sqlExceptSelect += " order by t.id DESC";
		return paginate(pageNo, pageSize, select, sqlExceptSelect);
	}
	public List<OrderGoods> getList3(int orderId){
		String sql="SELECT  t_goods.`id`,t_goods.`name`,t_goods.`img1_url`,t_goods.`postage`,\n" +
				"\tt_order_goods.`goods_sn`,\n" +
				"\tt_order_goods.`count`,t_order_goods.`price`,t_order_goods.`dis_price`,t_order_goods.`sku_info`\n" +
				"\tFROM t_order_goods  t_order_goods\n" +
				"\tLEFT JOIN t_sku_goods t_sku_goods ON t_sku_goods.`id`=t_order_goods.`sku_goods_id`\n" +
				"\tLEFT JOIN t_goods t_goods ON t_goods.`id`=t_sku_goods.`goods_id` \n" +
				"\tWHERE t_order_goods.`order_id`="+orderId;
		return find(sql);
	}

	public Page<OrderGoods> getBoughtGoods(int pageNo,int pageSize,int memberId){
		String sql="SELECT  t_goods.`id`,\n" +
				"t_goods.`name`,t_goods.`img1_url`,t_sku_goods.`goods_number`,t_order_goods.`sku_info`,t_order_goods.`price`,t_order_goods.`dis_price`\n" +
				"\n" +
				"FROM t_order_goods \n" +
				"LEFT JOIN t_sku_goods ON t_sku_goods.`id`=t_order_goods.`sku_goods_id`\n" +
				"LEFT JOIN t_goods ON t_goods.`id`=t_sku_goods.`goods_id`\n" +
				"LEFT JOIN t_order ON t_order_goods.`order_id`=t_order.`id`\n" +
				"WHERE t_order.`member_id`="+memberId+" GROUP BY t_goods.`id`";
		String select="SELECT  t_goods.`id`,t_brand.`name_en`,t_brand.`name_zh`,\n" +
				"t_goods.`name`,t_goods.`img1_url`,t_sku_goods.`goods_number`,t_order_goods.`sku_info`,t_order_goods.`price`,t_order_goods.`dis_price`";
		String where="FROM t_order_goods \n" +
				"LEFT JOIN t_sku_goods ON t_sku_goods.`id`=t_order_goods.`sku_goods_id`\n" +
				"LEFT JOIN t_goods ON t_goods.`id`=t_sku_goods.`goods_id`\n" +
				"LEFT JOIN t_order ON t_order_goods.`order_id`=t_order.`id`\n" +
				"Left JOIN t_brand t_brand on t_brand.`id`=t_goods.`brand_id`\n" +
				"WHERE t_order.`member_id`="+memberId+" GROUP BY t_goods.`id`";
		return paginate(pageNo,pageSize,select,where);
	}

	/**
	 * 获取品牌对应的出售sku商品单子
	 * @param brandId
	 * @return
	 */
	public List<OrderGoods> getListByBrandId(Integer brandId) {
		String sql = "select t.*" +
				" from t_order_goods AS t"+
				" LEFT JOIN t_sku_goods AS sg ON t.sku_goods_id= sg.id"+
				" LEFT JOIN t_goods AS g ON sg.goods_id= g.id"+
				" LEFT JOIN t_brand AS b ON g.brand_id= b.id"+
				" where b.id="+brandId;
		return dao.find(sql);
	}
	/**
	 * 获取主商品对应的出售sku商品单子
	 * @param goodsId
	 * @return
	 */
	public List<OrderGoods> getListByGoodsId(Integer goodsId) {
		String sql = "select t.*" +
				" from t_order_goods AS t"+
				" LEFT JOIN t_sku_goods AS sg ON t.sku_goods_id= sg.id"+
				" LEFT JOIN t_goods AS g ON sg.goods_id= g.id"+
				" where g.id="+goodsId;
		return dao.find(sql);
	}
}
