package com.up.infant.model;

import com.jfinal.plugin.activerecord.Db;
import com.up.common.utils.Sql;
import com.up.infant.model.base.BasePostageProvince;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostageProvince extends BasePostageProvince<PostageProvince> {
	public static final PostageProvince dao = new PostageProvince();
	public static final String table="t_postage_province";
	public static final String ptId="t_postage_province.pt_id";
	public static final String province="t_postage_province.province";
	public static final String postage="t_postage_province.postage";

	public void addBatch(List<PostageProvince> list){
		Db.batchSave(list,list.size());
	}
	public void updateBatch(List<PostageProvince> list){
		Db.batchUpdate(list,list.size());
	}
	public List<PostageProvince> getList(int pt_id){
		String sql= Sql.select("*")+Sql.from(table);
		if (pt_id>=0){
			Map<String,String> map=new HashMap<String, String>();
			map.put(ptId,pt_id+"");
			sql=sql+Sql.where(map);
		}
		return find(sql);
	}

	public void deleteBatch(int pt_id){
		List<PostageProvince> oldpp=getList(pt_id);
		Object[][] objs = new Object[oldpp.size()][1];
		for(int i = 0;i<oldpp.size();i++){
			objs[i][0] = oldpp.get(i).getId();
		}
		Db.batch("delete from t_postage_province where id = ?",objs,oldpp.size());
	}
}
