package com.up.infant.model;

import com.jfinal.plugin.activerecord.Db;
import com.up.common.utils.Sql;
import com.up.infant.model.base.BasePostageTpl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostageTpl extends BasePostageTpl<PostageTpl> {
	public static final PostageTpl dao = new PostageTpl();

	private static final String table="t_postage_tpl t_postage_tpl";
	private static final String id="t_postage_tpl.id";
	private static final String pgId="t_postage_tpl.pg_id";
	private static final String name="t_postage_tpl.name";
	private static final String expressage="t_postage_tpl.expressage";

	public List<PostageTpl> getList(int pg_id){
		String sql= Sql.select("*")+Sql.from(table);
		if (pg_id>=0){
			Map<String,String> map=new HashMap<String, String>();
			map.put(pgId,pg_id+"");
			sql=sql+Sql.where(map);
		}
		return find(sql);
	}

	public void deleteBatch(int pg_id){
		List<PostageTpl> oldpt=getList(pg_id);
		Object[][] objs = new Object[oldpt.size()][1];
		for(int i = 0;i<oldpt.size();i++){
			objs[i][0] = oldpt.get(i).getId();
			//批量删除该运费模板下的运费值设置
			PostageProvince.dao.deleteBatch(oldpt.get(i).getId());
		}
		Db.batch("delete from t_postage_tpl where id = ?",objs,oldpt.size());
	}

	public List<PostageTpl> getMax(String[] ids,String pro){
		String sql1="SELECT * FROM \n" +
				"\tt_postage_tpl \n" +
				"LEFT JOIN t_postage_province ON t_postage_province.`pt_id`=t_postage_tpl.`id`\n" +
				"WHERE t_postage_tpl.`pg_id`=8 AND t_postage_province.`province_name`='福建'";
		List<PostageTpl> postageTplList=new ArrayList<PostageTpl>();
		for (int i=0;i<ids.length;i++){
			String sql="select t_sys_config.`value`,t_postage_province.`postage`\n" +
					"from t_postage_tpl \n" +
					"left join t_postage_province on t_postage_province.`pt_id`=t_postage_tpl.`id`\n" +
					"Left join t_sys_config on t_sys_config.`id`=t_postage_tpl.`expressage`\n" +
					"where t_postage_tpl.`pg_id`="+ids[i]+" and t_postage_province.`province_name`='"+pro+"'";
			List<PostageTpl> list=find(sql);
			postageTplList.addAll(list);
		}
		return postageTplList;

	}
}
