package com.up.infant.model;

import com.up.common.utils.Sql;
import com.up.infant.model.base.BasePostageGroup;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostageGroup extends BasePostageGroup<PostageGroup> {
	public static final PostageGroup dao = new PostageGroup();

	public static final String table="t_postage_group t_postage_group";
	public static final String id="t_postage_group.id";
	public static final String name="t_postage_group.name";

	public List<PostageGroup> getList(){
		String sql= Sql.select("*")+Sql.from(table);
		return find(sql);
	}
}
