package com.up.infant.model;

import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseProvince;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Province extends BaseProvince<Province> {
	public static final Province dao = new Province();

	public List<Province> getList() {
		String sql= Sql.select("*")+Sql.from("t_province");
		return find(sql);
	}
}
