package com.up.infant.model;

import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseRegion;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Region extends BaseRegion<Region> {
	public static final Region dao = new Region();
	public List<Region> getList(int parentCode){
		String sql= "SELECT * FROM t_region WHERE parentCode = "+parentCode;
		return find(sql);
	}
}
