package com.up.infant.model;

import com.up.infant.model.base.BaseRepestory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Repestory extends BaseRepestory<Repestory> {
	public static final Repestory dao = new Repestory();
}
