package com.up.infant.model;

import com.up.infant.model.base.BaseStorageReturns;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StorageReturns extends BaseStorageReturns<StorageReturns> {
	public static final StorageReturns dao = new StorageReturns();
}
