package com.up.infant.model;

import com.jfinal.plugin.activerecord.Page;
import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseSysMessage;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMessage extends BaseSysMessage<SysMessage> {
	public static final SysMessage dao = new SysMessage();
	public static final String table="t_sys_message t_sys_message";
	public static final String id="t_sys_message.id";
	public static final String title="t_sys_message.title";
	public static final String content="t_sys_message.content";
	public static final String createTime="t_sys_message.create_time";

	public SysMessage getInfo(int pId){
		return findById(pId);
	}

	public Page<SysMessage> getList(int pageSize,int pageNo){
		return paginate(pageNo,pageSize,true, Sql.select(id,title,createTime,content),Sql.from(table)+Sql.orderBy(createTime,false));
	}
	public Page<SysMessage> getPageList(int pageSize,int pageNo){
		return paginate(pageNo,pageSize, Sql.select(id,title,createTime,content),Sql.from(table)+Sql.orderBy(createTime,false));
	}
	public Page<SysMessage> getPageList(int pageSize,int pageNo,int type){
		String select = "select *";
		String sqlExceptSelect = "from t_sys_message t where t.type="+type+
				" order by t.create_time DESC";

		return paginate(pageNo,pageSize, select,sqlExceptSelect);
	}
	public List<SysMessage> getByTime(String createTime){
		String sql="SELECT * FROM t_sys_message WHERE create_time >='"+createTime+"'";
		return  find(sql);

	}
}
