package com.up.infant.model;

import com.up.infant.model.base.BaseSystemMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemMessage extends BaseSystemMessage<SystemMessage> {
	public static final SystemMessage dao = new SystemMessage();
}
