package com.up.infant.model;

import com.up.infant.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

	public User isLogin(String name,String password){
		String sql="SELECT * FROM t_user WHERE name='"+name+"' AND password ='"+password+"'";
		User user=findFirst(sql);
		return user;
	}
}
