package com.up.infant.model;

import com.jfinal.plugin.activerecord.Db;
import com.up.common.utils.Sql;
import com.up.infant.model.base.BaseVipGrade;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VipGrade extends BaseVipGrade<VipGrade> {
	public static final VipGrade dao = new VipGrade();

    public void addBatch(List<VipGrade> gradeList) {
        Db.batchSave(gradeList,gradeList.size());
    }

    public List<VipGrade> getList() {
        String sql= "select * from t_vip_grade";
        return find(sql);
    }

    public void updateBatch(List<VipGrade> gradeList) {
        Db.batchUpdate(gradeList,gradeList.size());
    }

    public void deleteBatch(List<VipGrade> deleteGradeList) {
        Object[][] objs = new Object[deleteGradeList.size()][1];
        for(int i = 0;i<deleteGradeList.size();i++){
            objs[i][0] = deleteGradeList.get(i).getId();
        }
        Db.batch("delete from t_vip_grade where id = ?",objs,deleteGradeList.size());
    }

    public VipGrade getFistGrade(){
        String sql="SELECT * FROM t_vip_grade WHERE 0<=amount ORDER BY amount\n" +
                "LIMIT 1";
        return findFirst(sql);
    }



}
